# Generated by Django 5.2.7 on 2026-09-13 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explore", "0007_remove_review_unique_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="placereview",
            unique_together={("user", "place")},
        ),
    ]
